### ISSUE TITLE
Comments/literate notation for tree notation?

### ISSUE THREAD

**Issue by wizzard0** [treenotation/faq.treenotation.org#3]
Not sure if this repo is the best place to ask about the tree notation itself, but I guess the closest one.

How do I use comments (parseable or not parseable?) in tree notation? Any convention on that?

Same for literate programming, where it's assumed that what you write is description unless specifially marked as code

Can't find both use cases neither in faq nor in various examples

**Comment by breck7** [comment]
Tree Notation at the best level does not have a concept of comments (it's very basic), so comments only happen at the higher Tree Language level.

The general best practice I've found is to just use the keyword "comment".

For example:

https://jtree.treenotation.org/designer/#grammar%0A%20anyCell%0A%20blankCell%0A%20bulletPointCell%0A%20%20highlightScope%20keyword%0A%20codeCell%0A%20%20highlightScope%20comment%0A%20commentCell%0A%20%20highlightScope%20comment%0A%20keywordCell%0A%20%20highlightScope%20keyword%0A%20textCell%0A%20%20highlightScope%20string%0A%20permalinkCell%0A%20%20highlightScope%20string%0A%20urlCell%0A%20%20highlightScope%20constant.language%0A%20errorNode%0A%20%20baseNodeType%20errorNode%0A%20scrolldownNode%0A%20%20extensions%20scroll%0A%20%20description%20A%20Tree%20Language%20that%20compiles%20to%20HTML.%20An%20extensible%20alternative%20to%20Markdown.%0A%20%20root%0A%20%20inScope%20abstractTopLevelNode%20blankLineNode%0A%20%20catchAllNodeType%20quickParagraphNode%0A%20%20compilesTo%20html%0A%20%20example%0A%20%20%20title%20Hello%20world%0A%20%20%20title2%20This%20is%20Scrolldown%0A%20%20%20%0A%20%20%20paragraph%0A%20%20%20%20It%20compiles%20to%20HTML.%20Blank%20lines%20get%20turned%20into%20brs.%0A%20%20%20%0A%20%20%20code%0A%20%20%20%20%2F%2F%20You%20can%20add%20code%20as%20well.%0A%20%20%20%20print(%22Hello%20world%22)%0A%20abstractTopLevelNode%0A%20%20abstract%0A%20%20cells%20keywordCell%0A%20abstractTopLevelSingleMetaNode%0A%20%20abstract%0A%20%20description%20Use%20these%20keywords%20once%20per%20file.%0A%20%20extends%20abstractTopLevelNode%0A%20paragraphNode%0A%20%20description%20Prose%20content.%0A%20%20catchAllNodeType%20paragraphContentNode%0A%20%20extends%20abstractTopLevelNode%0A%20%20crux%20paragraph%0A%20%20javascript%0A%20%20%20compile()%20%7B%0A%20%20%20%20return%20%60%3Cp%3E%24%7Bthis.childrenToString()%7D%3C%2Fp%3E%60%0A%20%20%20%7D%0A%20paragraphContentNode%0A%20%20catchAllCellType%20textCell%0A%20codeNode%0A%20%20description%20A%20code%20block.%0A%20%20catchAllNodeType%20lineOfCodeNode%0A%20%20extends%20abstractTopLevelNode%0A%20%20javascript%0A%20%20%20compile()%20%7B%0A%20%20%20%20return%20%60%3Ccode%20class%3D%22scrollCodeBlock%22%3E%24%7Bthis.getIndentation()%20%2B%20%20this.childrenToString().replace(%2F%5C%3C%2Fg%2C%20%22%26lt%3B%22)%7D%3C%2Fcode%3E%60%0A%20%20%20%7D%0A%20%20crux%20code%0A%20codeWithLanguageNode%0A%20%20description%20Use%20this%20to%20specify%20the%20language%20of%20the%20code%20block%2C%20such%20as%20csvCode%20or%20rustCode.%0A%20%20extends%20codeNode%0A%20%20pattern%20%5E%5Ba-zA-Z0-9_%5D%2BCode%24%0A%20lineOfCodeNode%0A%20%20catchAllCellType%20codeCell%0A%20%20catchAllNodeType%20lineOfCodeNode%0A%20quoteNode%0A%20%20description%20A%20blockquote.%0A%20%20catchAllNodeType%20quoteLineNode%0A%20%20extends%20abstractTopLevelNode%0A%20%20javascript%0A%20%20%20compile()%20%7B%0A%20%20%20%20return%20%60%3Cblockquote%3E%24%7Bthis.getIndentation()%20%2B%20this.childrenToString()%7D%3C%2Fblockquote%3E%60%0A%20%20%20%7D%0A%20%20crux%20quote%0A%20quoteLineNode%0A%20%20catchAllCellType%20anyCell%0A%20%20catchAllNodeType%20quoteLineNode%0A%20rowNode%0A%20%20catchAllCellType%20textCell%0A%20%20javascript%0A%20%20%20toRow(columnCount)%20%7B%0A%20%20%20%20%20const%20words%20%3D%20this.getWords()%0A%20%20%20%20%20let%20str%20%3D%20%22%22%0A%20%20%20%20%20let%20column%20%3D%200%0A%20%20%20%20%20while%20(column%20%3C%20columnCount)%20%7B%0A%20%20%20%20%20%20%20column%2B%2B%0A%20%20%20%20%20%20%20const%20content%20%3D%20columnCount%20%3D%3D%3D%20column%20%3F%20words.slice(columnCount%20-%201).join(%22%20%22)%20%3A%20words%5Bcolumn%20-%201%5D%0A%20%20%20%20%20%20%20const%20linkified%20%3D%20jtree.Utils.linkify(content)%0A%20%20%20%20%20%20%20str%20%2B%3D%20%60%3Ctd%3E%24%7Blinkified%7D%3C%2Ftd%3E%5Cn%60%0A%20%20%20%20%20%7D%0A%20%20%20%20%20return%20str%0A%20%20%20%7D%0A%20tableNode%0A%20%20crux%20table%0A%20%20description%20Space%20Separated%20Values%20table%20with%20linkify.%20Last%20column%20is%20a%20catch%20all.%0A%20%20catchAllNodeType%20rowNode%0A%20%20extends%20abstractTopLevelNode%0A%20%20javascript%0A%20%20%20get%20tableHeader()%20%7B%0A%20%20%20%20%20const%20header%20%3D%20this.nodeAt(0)%0A%20%20%20%20%20return%20header%20%3F%20header.getWords().map(word%20%3D%3E%20%60%3Cth%3E%24%7Bword%7D%3C%2Fth%3E%5Cn%60)%20%3A%20%5B%5D%0A%20%20%20%7D%0A%20%20%20getTableBody(columnCount)%20%7B%0A%20%20%20%20%20return%20this.getTopDownArray().slice(1).map(node%20%3D%3E%20%60%3Ctr%3E%24%7Bnode.toRow(columnCount)%7D%3C%2Ftr%3E%60).join(%22%5Cn%22)%0A%20%20%20%7D%0A%20%20%20compile()%20%7B%0A%20%20%20%20%20%20const%20tableHeader%20%3D%20this.tableHeader%0A%20%20%20%20%20%20return%20%60%3Ctable%3E%3Cthead%3E%3Ctr%3E%24%7BtableHeader.join(%22%5Cn%22)%7D%3C%2Ftr%3E%3C%2Fthead%3E%5Cn%3Ctbody%3E%24%7Bthis.getTableBody(tableHeader.length)%7D%3C%2Ftbody%3E%3C%2Ftable%3E%60%0A%20%20%20%20%7D%0A%20linkNode%0A%20%20cells%20urlCell%0A%20%20catchAllCellType%20textCell%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Cli%3E%3Ca%20href%3D%22%7BurlCell%7D%22%3E%7BtextCell%7D%3C%2Fa%3E%3C%2Fli%3E%0A%20linksNode%0A%20%20description%20Links%20listed%20as%3A%20%7Burl%7D%20%7Blink%20text%7D%0A%20%20catchAllNodeType%20linkNode%0A%20%20crux%20links%0A%20%20extends%20abstractTopLevelNode%0A%20%20compiler%0A%20%20%20stringTemplate%20%0A%20%20%20openChildren%20%3Cul%3E%0A%20%20%20closeChildren%20%3C%2Ful%3E%0A%20listItemNode%0A%20%20cells%20bulletPointCell%0A%20%20catchAllCellType%20textCell%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Cli%3E%7BtextCell%7D%3C%2Fli%3E%0A%20listNode%0A%20%20description%20An%20unordered%20list.%0A%20%20catchAllNodeType%20listItemNode%0A%20%20crux%20list%0A%20%20extends%20abstractTopLevelNode%0A%20%20compiler%0A%20%20%20stringTemplate%20%0A%20%20%20openChildren%20%3Cul%3E%0A%20%20%20closeChildren%20%3C%2Ful%3E%0A%20orderedListNode%0A%20%20description%20An%20ordered%20list.%0A%20%20extends%20listNode%0A%20%20crux%20orderedList%0A%20%20compiler%0A%20%20%20stringTemplate%20%0A%20%20%20openChildren%20%3Col%3E%0A%20%20%20closeChildren%20%3C%2Fol%3E%0A%20blankLineNode%0A%20%20description%20Blank%20lines%20compile%20to%20nothing%20in%20the%20HTML.%0A%20%20cells%20blankCell%0A%20%20compiler%0A%20%20%20stringTemplate%20%0A%20%20pattern%20%5E%24%0A%20%20tags%20doNotSynthesize%0A%20dateCell%0A%20%20highlightScope%20string%0A%20commentNode%0A%20%20description%20Will%20not%20appear%20in%20the%20compiled%20HTML.%0A%20%20catchAllCellType%20commentCell%0A%20%20extends%20abstractTopLevelNode%0A%20%20crux%20comment%0A%20%20javascript%0A%20%20%20compile()%20%7B%0A%20%20%20%20return%20%60%60%0A%20%20%20%7D%0A%20%20catchAllNodeType%20commentLineNode%0A%20commentLineNode%0A%20%20catchAllCellType%20commentCell%0A%20permalinkNode%0A%20%20description%20When%20compiling%2C%20Scroll%20will%20save%20this%20article%20to%20%7Bpermalink%7D.html%0A%20%20crux%20permalink%0A%20%20extends%20abstractTopLevelSingleMetaNode%0A%20%20cells%20keywordCell%20permalinkCell%0A%20%20compiler%0A%20%20%20stringTemplate%20%0A%20titleNode%0A%20%20catchAllCellType%20textCell%0A%20%20description%20Title%20of%20the%20article.%0A%20%20extends%20abstractTopLevelSingleMetaNode%0A%20%20compiler%0A%20%20%20stringTemplate%20%0A%20%20crux%20title%0A%20%20javascript%0A%20%20%20compile(spaces)%20%7B%0A%20%20%20%20const%20title%20%3D%20this.getContent()%0A%20%20%20%20const%20permalink%20%3D%20this.getRootNode().get(%22permalink%22)%20%7C%7C%20jtree.Utils.stringToPermalink(this.getContent())%0A%20%20%20%20return%20%60%3Ch1%3E%3Ca%20href%3D%22%24%7Bpermalink%7D.html%22%3E%24%7Btitle%7D%3C%2Fa%3E%3C%2Fh1%3E%60%0A%20%20%20%7D%0A%20abstractTitleNode%0A%20%20description%20A%20subheader.%0A%20%20catchAllCellType%20textCell%0A%20%20extends%20abstractTopLevelNode%0A%20%20catchAllNodeType%20multilineTitleNode%0A%20%20javascript%0A%20%20%20compile()%20%7B%0A%20%20%20%20const%20tag%20%3D%20this.getFirstWord().replace(%22title%22%2C%20%22h%22)%0A%20%20%20%20const%20children%20%3D%20this.childrenToString()%20%3F%20%22%20%22%20%2B%20this.childrenToString()%20%3A%20%22%22%0A%20%20%20%20return%20%60%3C%24%7Btag%7D%3E%24%7Bthis.getContent()%20%2B%20children%7D%3C%2F%24%7Btag%7D%3E%60%0A%20%20%20%7D%0A%20multilineTitleNode%0A%20%20catchAllCellType%20textCell%0A%20title2Node%0A%20%20extends%20abstractTitleNode%0A%20%20crux%20title2%0A%20title3Node%0A%20%20extends%20abstractTitleNode%0A%20%20crux%20title3%0A%20title4Node%0A%20%20extends%20abstractTitleNode%0A%20%20crux%20title4%0A%20title5Node%0A%20%20extends%20abstractTitleNode%0A%20%20crux%20title5%0A%20title6Node%0A%20%20extends%20abstractTitleNode%0A%20%20crux%20title6%0A%20dateNode%0A%20%20catchAllCellType%20dateCell%0A%20%20description%20Date%20the%20article%20was%20first%20published.%0A%20%20extends%20abstractTopLevelSingleMetaNode%0A%20%20crux%20date%0A%20%20javascript%0A%20%20%20compile(spaces)%20%7B%0A%20%20%20%20const%20dayjs%20%3D%20require(%22dayjs%22)%0A%20%20%20%20const%20dateCell%20%3D%20dayjs(this.getContent()).format(%60MMMM%20D%2C%20YYYY%60)%0A%20%20%20%20return%20%60%3Cdiv%20class%3D%22scrollArticleDate%22%3E%24%7BdateCell%7D%20%E2%80%94%20%3C%2Fdiv%3E%60%0A%20%20%20%7D%0A%20quickParagraphNode%0A%20%20description%20A%20catch%20all%20block.%20This%20may%20be%20removed%20in%20future%20versions.%0A%20%20catchAllCellType%20textCell%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Cp%3E%7BtextCell%7D%3C%2Fp%3E%0Asample%0A%20paragraph%0A%20%20Hello%20world%0A%20%0A%20comment%0A%20%20This%20is%20a%20comment%0A%20%20It%20can%20span%20multiple%20lines%0A%20%20When%20you%20click%20%22Compile%22%20above%2C%20it%20will%20not%20be%20compiled.

**Comment by breck7** [comment]
It's a really good idea to have literate versions of some of these languages. Hadn't thought of that.

**Comment by wizzard0** [comment]
Ah, so the basic tree language is closer to a (m-expression) tree serialization format. Thanks! Also all this thing is in some way very similar to APL (can't explain in more detail though)
